layout_spectrum: 0.9834077
typography_spectrum: 0.728583
color:
  saturation: 0.9561129
  lightness: 0.9829223
  brandStrength: 0.536508
  rhythmicContrast: 0.5466083
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Coroplast Boats
